
var issuerBoxContent=undefined;var recipientBoxContent=undefined;var issuerAccountWrapper=undefined;var recipientAccountWrapper=undefined;var issuerAccountUlArray=undefined;var recipientAccountUlArray=undefined;var tranfertPage=false;function initVariables(){issuerAccountWrapper=document.getElementById("issuer-account-list");recipientAccountWrapper=document.getElementById("recipient-account-list");issuerBoxContent=document.getElementById("issuerBoxContent");recipientBoxContent=document.getElementById("recipientBoxContent");if(!(issuerAccountWrapper&&recipientAccountWrapper&&issuerBoxContent&&recipientBoxContent)){return false;}
else{if(issuerAccountWrapper){issuerAccountUlArray=issuerAccountWrapper.getElementsByTagName("td");}
if(recipientAccountWrapper){recipientAccountUlArray=recipientAccountWrapper.getElementsByTagName("td");}
tranfertPage=true;}}
function equalizingHeights(array){if(array!=undefined){array[0].style.height="";maxHeight=array[0].offsetHeight;for(var i=1;i<array.length;i++){array[i].style.height="";array[i].offsetHeight>maxHeight?maxHeight=array[i].offsetHeight:maxHeight=maxHeight;}
for(var i=0;i<array.length;i++){array[i].style.height=maxHeight+"px";}}}
var equalizingHeightsOnselectBoxesTable=function(){if(document.getElementById('selectBoxesTable')){equalizingHeights(document.getElementById('selectBoxesTable').getElementsByTagName('td'));}};var equalizingHeightsIssuersPopUp=function(){setTimeout(function(){if(document.getElementById("issuer-account-list").style.display=="block"){equalizingHeights(issuerAccountWrapper.getElementsByTagName('td'));}},1000);};var equalizingHeightsRecipientsPopUp=function(){setTimeout(function(){if(document.getElementById("recipient-account-list").style.display=="block"){equalizingHeights(recipientAccountWrapper.getElementsByTagName('td'));}},1000);};function setPlaceHolders(){var amount=document.getElementById("amountInteger");var wording=document.getElementById("wording");if(amount){if(isAndroidBrowser()){amount.onfocus=function(){this.setAttribute('type','number');};amount.onblur=function(){this.setAttribute('type','text');};}
amount.setAttribute('type','text');amount.setAttribute("placeholder","Montant");}
if(wording){wording.setAttribute("placeholder","Libellé");}}
function setAttributesToAccounts(mode,exception){if(!tranfertPage){return false;}
else{if(mode=="issuer"){for(var i=0;i<issuerAccountUlArray.length;i++){var anchor=issuerAccountUlArray[i].getElementsByTagName('a')[0];anchor.setAttribute("data-account-id",anchor.getAttribute("id"));anchor.setAttribute("data-related-to","sIssuer");anchor.setAttribute("data-label-id","issuerLabel");if(anchor!=exception){anchor.setAttribute("href","#");anchor.setAttribute("data-bk-rel","close");anchor.style.opacity="1";}}}
else if(mode=="recipient"){for(var i=0;i<recipientAccountUlArray.length;i++){var anchor=recipientAccountUlArray[i].getElementsByTagName('a')[0];anchor.setAttribute("data-account-id",anchor.getAttribute("id"));anchor.setAttribute("data-related-to","sRecipient");anchor.setAttribute("data-label-id","recipientLabel");if(anchor!=exception){anchor.setAttribute("href","#");anchor.setAttribute("data-bk-rel","close");anchor.style.opacity="1";}}}}}
function customReplace(from,to,url,transition){Bk.initContext();Bk.replace({content:{from:from,to:to,url:url,transition:transition}},this);Bk.releaseContext();return false;}
function updateBoxContent(anchor,mode){if(mode=="issuer"){issuerBoxContentSpan=issuerBoxContent.querySelector("a span");customReplace(issuerBoxContentSpan.id,anchor.id+"-inner-wrapper","/transfers/newTransfer","none");}
else if(mode=="recipient"){recipientBoxContentSpan=recipientBoxContent.querySelector("a span");customReplace(recipientBoxContentSpan.id,anchor.id+"-inner-wrapper","/transfers/newTransfer","none");}}
function updateHiddenInputValue(anchor,mode){if(mode=="issuer"){issuerHidden=document.getElementById('sIssuer');issuerHidden.setAttribute("value",anchor.getAttribute("id"));}
else if(mode=="recipient"){recipientHidden=document.getElementById('sRecipient');recipientHidden.setAttribute("value",anchor.getAttribute("id"));}}
function isAnchorDisabled(anchor){if(anchor.getAttribute("href")=="#"&&anchor.getAttribute("data-bk-rel")=="close"&&anchor.style.opacity=="1"){return false;}
else{return true;}}
function disableSelectedAccounts(){if(!(issuerBoxContent&&recipientBoxContent)){return false;}
if(!(issuerBoxContent.firstElementChild.firstElementChild&&recipientBoxContent.firstElementChild.firstElementChild)){return false;}
var issuerBoxContentSpan=issuerBoxContent.firstElementChild.firstElementChild;var recipientBoxContentSpan=recipientBoxContent.firstElementChild.firstElementChild;if(issuerBoxContentSpan.id!="issuer-trigger-inner-wrapper"){var issuerBoxContentSpanIdFirstPart=issuerBoxContentSpan.id.split("-")[0];var anchor=document.getElementById(issuerBoxContentSpanIdFirstPart);if(anchor.hasAttribute("href")){anchor.removeAttribute("href");}
if(anchor.hasAttribute("data-bk-rel")){anchor.removeAttribute("data-bk-rel");}
anchor.style.opacity="0.2";}
if(recipientBoxContentSpan.id!="recipient-trigger-inner-wrapper"){var recipientBoxContentSpanIdFirstPart=recipientBoxContentSpan.id.split("-")[0];var anchor=document.getElementById(recipientBoxContentSpanIdFirstPart);if(anchor.hasAttribute("href")){anchor.removeAttribute("href");}
if(anchor.hasAttribute("data-bk-rel")){anchor.removeAttribute("data-bk-rel");}
anchor.style.opacity="0.2";}}
function handleClickOnAccount(anchor,mode){if(!isAnchorDisabled(anchor)){updateBoxContent(anchor,mode);updateHiddenInputValue(anchor,mode);setAttributesToAccounts(mode,anchor);}}
var handleClickOnAccountForIssuer=function(e){el=retrieveAnchorTag(e);if(el){handleClickOnAccount(el,"issuer");}};var handleClickOnAccountForRecipient=function(e){el=retrieveAnchorTag(e);if(el){handleClickOnAccount(el,"recipient");}};function retrieveAnchorTag(event){var el=event.target||event.srcElement;var depth=0;while(el.nodeName.toLowerCase()!=='a'&&depth<4){el=el.parentNode;}
if(el.nodeName.toLowerCase()==='a'){return el;}
else{return false;}}
var cleanListenersOnAccount=function(anchor){newAnchor=anchor.cloneNode(true);anchorParent=anchor.parentElement;anchorParent.replaceChild(newAnchor,anchor);return newAnchor;};var setListenersOnAccount=function(){if(!tranfertPage){return false;}
else{if(window.addEventListener){for(var i=0;i<issuerAccountUlArray.length;i++){var anchor=issuerAccountUlArray[i].getElementsByTagName('a')[0];anchor.addEventListener("click",handleClickOnAccountForIssuer,false);}
for(var i=0;i<recipientAccountUlArray.length;i++){var anchor=recipientAccountUlArray[i].getElementsByTagName('a')[0];anchor.addEventListener("click",handleClickOnAccountForRecipient,false);}}
else{for(var i=0;i<issuerAccountUlArray.length;i++){var anchor=issuerAccountUlArray[i].getElementsByTagName('a')[0];anchor.attachEvent("onclick",handleClickOnAccountForIssuer);}
for(var i=0;i<recipientAccountUlArray.length;i++){var anchor=recipientAccountUlArray[i].getElementsByTagName('a')[0];anchor.attachEvent("onclick",handleClickOnAccountForRecipient);}}}};var setListenersOnSelectBoxes=function(){if(!tranfertPage){return false;}
else{if(document.getElementById('issuer-trigger')&&document.getElementById('recipient-trigger')){if(window.addEventListener){document.getElementById('issuer-trigger').addEventListener("click",equalizingHeightsIssuersPopUp,false);document.getElementById('recipient-trigger').addEventListener("click",equalizingHeightsRecipientsPopUp,false);}
else{document.getElementById('issuer-trigger').attachEvent("onclick",equalizingHeightsIssuersPopUp);document.getElementById('recipient-trigger').attachEvent("onclick",equalizingHeightsRecipientsPopUp);}}}};var initTransferBehaviour=function(){initVariables();if(!tranfertPage){return false;}
else{equalizingHeightsOnselectBoxesTable();setListenersOnSelectBoxes();setPlaceHolders();setAttributesToAccounts("issuer");setAttributesToAccounts("recipient");setListenersOnAccount();disableSelectedAccounts();Bk.Event.onOrientationChange(equalizingHeightsOnselectBoxesTable);Bk.Event.onOrientationChange(equalizingHeightsRecipientsPopUp);Bk.Event.onOrientationChange(equalizingHeightsIssuersPopUp);}
if(modify){equalizingHeightsOnselectBoxesTable();var issuer=document.getElementById('sIssuer').value;var recipient=document.getElementById('sRecipient').value;customReplace("issuer-trigger-inner-wrapper",issuer+"-inner-wrapper","/transfers/newTransfer","none");customReplace("recipient-trigger-inner-wrapper",recipient+"-inner-wrapper","/transfers/newTransfer","none");Bk.Event.onOrientationChange(equalizingHeightsOnselectBoxesTable);Bk.Event.onOrientationChange(equalizingHeightsRecipientsPopUp);Bk.Event.onOrientationChange(equalizingHeightsIssuersPopUp);}};var isAndroidBrowser=function(){var nua=navigator.userAgent;var is_android=((nua.indexOf('Mozilla/5.0')>-1&&nua.indexOf('Android ')>-1&&nua.indexOf('AppleWebKit')>-1)&&!(nua.indexOf('Chrome')>-1));return is_android;};Bk.onPageLoaded(initTransferBehaviour);